NS_ERROR_UNKNOWN_HOST error talking to auth server
Based off of https://support.mozilla.org/en-US/questions/1068465

First:
https://pastebin.mozilla.org/8837866
Second After disconnecting and repairing:
https://pastebin.mozilla.org/8837999

1435581688734 FirefoxAccounts DEBUG getKeyPair: already have a keyPair
1435581688734 FirefoxAccounts DEBUG getCertificateSigned: true true
1435581688804 Hawk WARN hawk request error: [Exception... "NS_ERROR_UNKNOWN_HOST" nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)" location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465" data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:465 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < this.BrowserIDManager.prototype._getAuthenticationHeader()@resource://gre/modules/services-sync/browserid_identity.js:656 < Res__createRequest()@resource://services-sync/resource.js:175 < _doRequest()@resource://services-sync/resource.js:200 < Res__request()@resource://services-sync/resource.js:404 < Res_get()@resource://services-sync/resource.js:429 < Sync11Service.prototype._fetchInfo()@resource://gre/modules/services-sync/service.js:553 < sync()@resource://services-sync/stages/enginesync.js:77 < onNotify()@resource://gre/modules/services-sync/service.js:1295 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1285 < sync/<()@resource://gre/modules/services-sync/service.js:1277 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1265 < <file:unknown>
1435581688805 Sync.RESTResponse DEBUG Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)" location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643" data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < _onComplete()@resource://services-common/hawkclient.js:215 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < this.BrowserIDManager.prototype._getAuthenticationHeader()@resource://gre/modules/services-sync/browserid_identity.js:656 < Res__createRequest()@resource://services-sync/resource.js:175 < _doRequest()@resource://services-sync/resource.js:200 < Res__request()@resource://services-sync/resource.js:404 < Res_get()@resource://services-sync/resource.js:429 < Sync11Service.prototype._fetchInfo()@resource://gre/modules/services-sync/service.js:553 < sync()@resource://services-sync/stages/enginesync.js:77 < onNotify()@resource://gre/modules/services-sync/service.js:1295 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1285 < sync/<()@resource://gre/modules/services-sync/service.js:1277 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1265 < <file:unknown>
1435581688805 Sync.RESTResponse DEBUG Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)" location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 659" data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:659 < _onComplete()@resource://services-common/hawkclient.js:218 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < this.BrowserIDManager.prototype._getAuthenticationHeader()@resource://gre/modules/services-sync/browserid_identity.js:656 < Res__createRequest()@resource://services-sync/resource.js:175 < _doRequest()@resource://services-sync/resource.js:200 < Res__request()@resource://services-sync/resource.js:404 < Res_get()@resource://services-sync/resource.js:429 < Sync11Service.prototype._fetchInfo()@resource://gre/modules/services-sync/service.js:553 < sync()@resource://services-sync/stages/enginesync.js:77 < onNotify()@resource://gre/modules/services-sync/service.js:1295 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1285 < sync/<()@resource://gre/modules/services-sync/service.js:1277 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1265 < <file:unknown>
1435581688805 Hawk DEBUG (Response) /certificate/sign: code: null - Status text: null
1435581688805 Sync.RESTResponse TRACE Processing response headers.
1435581688805 Sync.RESTResponse DEBUG Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)" location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693" data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:311 < _onComplete()@resource://services-common/hawkclient.js:225 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 <


...
1435581688807 Sync.Status DEBUG Status.login: success.login => error.login.reason.network
1435581688807 Sync.Status DEBUG Status.service: success.status_ok => error.login.failed
1435581688811 Sync.BrowserIDManager ERROR Failed to fetch a token for authentication: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\" nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\" location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\" data: no]","message":null,"code":null,"errno":null}
1435581688828 Sync.Status DEBUG Status.sync: success.sync => error.login.reason.network
1435581688828 Sync.Status DEBUG Status.service: error.login.failed => error.sync.failed
1435581688829 Sync.SyncScheduler DEBUG Next sync in 3600000 ms.

What ha been troubleshooted so far:
* Disconnected the account
* Repaired other part of the profile
