Pause on Exceptions doe not pause after reopening devtools
Test case: http://codepen.io/anon/pen/jWJExa

1. Open devtools on Debugger tab
2. Enable "Pause on Exceptions" in the Debugger option
3. Close devtools
4. Open devtools
5. Click the "Test Exceptions" button
6. Debugger should break on the uncaught exception

Expected results:

When devtools are opened to the Debugger panel, the debugger should break on the line that throw the exception.


Actual results:

Debugger doe not break. Console report "uncaught exception: ex". Notice that Pause on Exceptions is still ticked.


Affects:

Firefox Aurora 46.0a2 build 20160214004015
Firefox Nightly 47.0a1 build 20160214030236

Tested on Windows 7 SP1 x64, with clean Firefox profiles.


Works correctly on:

Firefox 44.0.1 build 20160205155049
Chrome 48.0.2564.109 m
Internet Explorer 11.0.9600.18204, update 11.0.28


Notes:

Pause on Exceptions work when first enabled (e.g. after step 2 above). It's only after closing and re-opening the devtools, or the browser a a whole, that it stop working.

Disabling and re-enabling Pause on Exceptions works, until the panel is closed.

A wild guess without having seen the source: perhaps the debugger exception handler is only attached when the option is first enabled, and not when the debugger is (re)opened?

This appears to be a regression from the last week or two. I first noticed it occurring on Aurora after an update within the last week, but I don't always keep it up to date. Possibly related to the new always-on debugger?
